steps:
  # Build dell'immagine Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mlops-breast-cancer:$COMMIT_SHA', '.']

  # Push dell'immagine al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mlops-breast-cancer:$COMMIT_SHA']

  # Deploy su Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mlops-breast-cancer-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mlops-breast-cancer:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'

# Immagini da salvare
images:
  - 'gcr.io/$PROJECT_ID/mlops-breast-cancer:$COMMIT_SHA'

# Timeout del build
timeout: '1200s'
