# Usa l'immagine ufficiale Prefect
FROM prefecthq/prefect:2.14.0-python3.9

# Esponi porta Prefect
EXPOSE 4200

# Comando di avvio Prefect (già configurato nell'immagine ufficiale)
CMD ["prefect", "server", "start", "--host", "0.0.0.0", "--port", "4200"]
